#!/bin/sh
#qcd install 
# changed by zengxianbo @Mon Dec 28 13:16:39 CST 2015
#written by xiewei 2004 

setup_content=$HOME/.qcd
history_dir=$setup_content/history_dir
bin_content=$HOME/bin
prof_content=$HOME/.profile.d

setup()
{
    if [ -r $history_dir ]      #????$history_dir ?Ե?ǰ?û??ɶ?
    then	
 	echo -n "You have installed qcd , overwrite it(y\Y or q\Q or n\N)? "
 	while read choice
 	do
	    if [ "$choice" = "y"  -o  "$choice" = "Y" ] # like first install
	    then
	        break
	    fi	

	    if [ "$choice" = "q"  -o  "$choice" = "Q" ]  # quit
	    then
	        echo "Nothing to do!"
	        exit 1
	    fi
               
	    if [ "$choice" = "n"  -o  "$choice" = "N" ]  # just overwrite qcd qcd.sh
	    then
	        cp -f ./qcd $bin_content/
		cp -f ./qcd.sh $prof_content/
		echo "install qcd OK, but do not overwrite it!"
	        echo "version is 1.00"
	        exit 1
	    fi	

	    echo -n "You have installed qcd, overwrite it(y\Y or q\Q or n\N)? " 
	done
    fi
    
    if [ -r $setup_content ]
    then
	:
    else
	mkdir $setup_content
    fi
    
    cp -f ./qcd $bin_content/
    cp -f ./history_dir $setup_content/
    cp -f ./qcd.sh $prof_content/
}

delete()
{
    [ -r $history_dir ] || [ -r $bin_content ] || \
    ! echo "Your computer has not qcd!" || ! echo "Nothing to do!"
    
    echo -n "Are you sure to delete qcd(y\Y or q\Q)? "
    while read choice
    do
        if [ "$choice" = "y"  -o  "$choice" = "Y" ]  
        then
            break
        fi	
	
	if [ "$choice" = "q"  -o  "$choice" = "Q" ]  
	then
	    echo "Nothing to do!"
	    exit 1
	fi
	
	echo -n "Are you sure to delete qcd(y\Y or q\Q)? "
    done

    rm -rf $setup_content
    rm -f  $bin_content/qcd
    rm -f  $prof_content/qcd.sh
}

usage()
{
    echo "<install> install qcd on your computer."
    echo "<install del> delete qcd from your computer."
    exit 1
}


if [ $# -eq 0 ]    #?????????Ĳ???????Ϊ0?
then
    if [ ! -d $prof_content ]; then
        mkdir $prof_content
    fi
    setup
    echo "install qcd OK!"
    echo "version is 1.00"
    exit 1
fi    

if [ $# -gt 1 ]    #?????????Ĳ???????????0
then
    usage
fi    

case $1 in        #?????????ĵ?һ????????del
del)
    delete
    echo "have delete qcd OK!"
    ;;
*)
    usage    #??ʾ??Ϣ
    ;;
esac


